################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (12.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
H:/stm32ai-modelzoo-2.1.0/stm32ai_application_code/object_detection/Drivers/BSP/Components/mt25tl01g/mt25tl01g.c \
H:/stm32ai-modelzoo-2.1.0/stm32ai_application_code/object_detection/Drivers/BSP/Components/nt35510/nt35510.c \
H:/stm32ai-modelzoo-2.1.0/stm32ai_application_code/object_detection/Drivers/BSP/Components/nt35510/nt35510_reg.c \
H:/stm32ai-modelzoo-2.1.0/stm32ai_application_code/object_detection/Drivers/BSP/Components/otm8009a/otm8009a.c \
H:/stm32ai-modelzoo-2.1.0/stm32ai_application_code/object_detection/Drivers/BSP/Components/otm8009a/otm8009a_reg.c \
H:/stm32ai-modelzoo-2.1.0/stm32ai_application_code/object_detection/Drivers/BSP/Components/ov5640/ov5640.c \
H:/stm32ai-modelzoo-2.1.0/stm32ai_application_code/object_detection/Drivers/BSP/Components/ov5640/ov5640_reg.c \
H:/stm32ai-modelzoo-2.1.0/stm32ai_application_code/object_detection/Drivers/BSP/Components/ov9655/ov9655.c \
H:/stm32ai-modelzoo-2.1.0/stm32ai_application_code/object_detection/Drivers/BSP/Components/ov9655/ov9655_reg.c 

OBJS += \
./Drivers/BSP/Components/mt25tl01g.o \
./Drivers/BSP/Components/nt35510.o \
./Drivers/BSP/Components/nt35510_reg.o \
./Drivers/BSP/Components/otm8009a.o \
./Drivers/BSP/Components/otm8009a_reg.o \
./Drivers/BSP/Components/ov5640.o \
./Drivers/BSP/Components/ov5640_reg.o \
./Drivers/BSP/Components/ov9655.o \
./Drivers/BSP/Components/ov9655_reg.o 

C_DEPS += \
./Drivers/BSP/Components/mt25tl01g.d \
./Drivers/BSP/Components/nt35510.d \
./Drivers/BSP/Components/nt35510_reg.d \
./Drivers/BSP/Components/otm8009a.d \
./Drivers/BSP/Components/otm8009a_reg.d \
./Drivers/BSP/Components/ov5640.d \
./Drivers/BSP/Components/ov5640_reg.d \
./Drivers/BSP/Components/ov9655.d \
./Drivers/BSP/Components/ov9655_reg.d 


# Each subdirectory must supply rules for building sources it contributes
Drivers/BSP/Components/mt25tl01g.o: H:/stm32ai-modelzoo-2.1.0/stm32ai_application_code/object_detection/Drivers/BSP/Components/mt25tl01g/mt25tl01g.c Drivers/BSP/Components/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32H747xx -DUSE_STM32H747I_DISCO -DCORE_CM7 -DDATA_IN_ExtSDRAM -DSTM32_IPL -DARM_MATH_CM7 -D__FPU_PRESENT=1U -DSTM32IPL -c -I../../../Inc/CM7 -I../../../../Network/Inc -I../../../../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../../../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/Components/Common -I../../../../../Drivers/BSP/Components/ov9655 -I../../../../../Drivers/BSP/Components/otm8009a -I../../../../../Drivers/BSP/Components/nt35510 -I../../../../../Drivers/BSP/Components/mt25tl01g -I../../../../../Utilities/Fonts -I../../../../../Utilities/lcd -I../../../../../Middlewares/ST/STM32_AI_Runtime/Inc -I../../../../../Middlewares/ST/STM32_ImageProcessing_Library/Inc -I../../../../../Middlewares/ST/STM32_Objdetect_Postprocess/Inc -I../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../Drivers/CMSIS/Core/Include -I../../../../../Drivers/CMSIS/Core/DSP/Include -I../../../../../Drivers/BSP/STM32H747I-DISCO -O3 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/Components/nt35510.o: H:/stm32ai-modelzoo-2.1.0/stm32ai_application_code/object_detection/Drivers/BSP/Components/nt35510/nt35510.c Drivers/BSP/Components/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32H747xx -DUSE_STM32H747I_DISCO -DCORE_CM7 -DDATA_IN_ExtSDRAM -DSTM32_IPL -DARM_MATH_CM7 -D__FPU_PRESENT=1U -DSTM32IPL -c -I../../../Inc/CM7 -I../../../../Network/Inc -I../../../../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../../../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/Components/Common -I../../../../../Drivers/BSP/Components/ov9655 -I../../../../../Drivers/BSP/Components/otm8009a -I../../../../../Drivers/BSP/Components/nt35510 -I../../../../../Drivers/BSP/Components/mt25tl01g -I../../../../../Utilities/Fonts -I../../../../../Utilities/lcd -I../../../../../Middlewares/ST/STM32_AI_Runtime/Inc -I../../../../../Middlewares/ST/STM32_ImageProcessing_Library/Inc -I../../../../../Middlewares/ST/STM32_Objdetect_Postprocess/Inc -I../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../Drivers/CMSIS/Core/Include -I../../../../../Drivers/CMSIS/Core/DSP/Include -I../../../../../Drivers/BSP/STM32H747I-DISCO -O3 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/Components/nt35510_reg.o: H:/stm32ai-modelzoo-2.1.0/stm32ai_application_code/object_detection/Drivers/BSP/Components/nt35510/nt35510_reg.c Drivers/BSP/Components/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32H747xx -DUSE_STM32H747I_DISCO -DCORE_CM7 -DDATA_IN_ExtSDRAM -DSTM32_IPL -DARM_MATH_CM7 -D__FPU_PRESENT=1U -DSTM32IPL -c -I../../../Inc/CM7 -I../../../../Network/Inc -I../../../../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../../../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/Components/Common -I../../../../../Drivers/BSP/Components/ov9655 -I../../../../../Drivers/BSP/Components/otm8009a -I../../../../../Drivers/BSP/Components/nt35510 -I../../../../../Drivers/BSP/Components/mt25tl01g -I../../../../../Utilities/Fonts -I../../../../../Utilities/lcd -I../../../../../Middlewares/ST/STM32_AI_Runtime/Inc -I../../../../../Middlewares/ST/STM32_ImageProcessing_Library/Inc -I../../../../../Middlewares/ST/STM32_Objdetect_Postprocess/Inc -I../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../Drivers/CMSIS/Core/Include -I../../../../../Drivers/CMSIS/Core/DSP/Include -I../../../../../Drivers/BSP/STM32H747I-DISCO -O3 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/Components/otm8009a.o: H:/stm32ai-modelzoo-2.1.0/stm32ai_application_code/object_detection/Drivers/BSP/Components/otm8009a/otm8009a.c Drivers/BSP/Components/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32H747xx -DUSE_STM32H747I_DISCO -DCORE_CM7 -DDATA_IN_ExtSDRAM -DSTM32_IPL -DARM_MATH_CM7 -D__FPU_PRESENT=1U -DSTM32IPL -c -I../../../Inc/CM7 -I../../../../Network/Inc -I../../../../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../../../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/Components/Common -I../../../../../Drivers/BSP/Components/ov9655 -I../../../../../Drivers/BSP/Components/otm8009a -I../../../../../Drivers/BSP/Components/nt35510 -I../../../../../Drivers/BSP/Components/mt25tl01g -I../../../../../Utilities/Fonts -I../../../../../Utilities/lcd -I../../../../../Middlewares/ST/STM32_AI_Runtime/Inc -I../../../../../Middlewares/ST/STM32_ImageProcessing_Library/Inc -I../../../../../Middlewares/ST/STM32_Objdetect_Postprocess/Inc -I../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../Drivers/CMSIS/Core/Include -I../../../../../Drivers/CMSIS/Core/DSP/Include -I../../../../../Drivers/BSP/STM32H747I-DISCO -O3 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/Components/otm8009a_reg.o: H:/stm32ai-modelzoo-2.1.0/stm32ai_application_code/object_detection/Drivers/BSP/Components/otm8009a/otm8009a_reg.c Drivers/BSP/Components/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32H747xx -DUSE_STM32H747I_DISCO -DCORE_CM7 -DDATA_IN_ExtSDRAM -DSTM32_IPL -DARM_MATH_CM7 -D__FPU_PRESENT=1U -DSTM32IPL -c -I../../../Inc/CM7 -I../../../../Network/Inc -I../../../../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../../../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/Components/Common -I../../../../../Drivers/BSP/Components/ov9655 -I../../../../../Drivers/BSP/Components/otm8009a -I../../../../../Drivers/BSP/Components/nt35510 -I../../../../../Drivers/BSP/Components/mt25tl01g -I../../../../../Utilities/Fonts -I../../../../../Utilities/lcd -I../../../../../Middlewares/ST/STM32_AI_Runtime/Inc -I../../../../../Middlewares/ST/STM32_ImageProcessing_Library/Inc -I../../../../../Middlewares/ST/STM32_Objdetect_Postprocess/Inc -I../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../Drivers/CMSIS/Core/Include -I../../../../../Drivers/CMSIS/Core/DSP/Include -I../../../../../Drivers/BSP/STM32H747I-DISCO -O3 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/Components/ov5640.o: H:/stm32ai-modelzoo-2.1.0/stm32ai_application_code/object_detection/Drivers/BSP/Components/ov5640/ov5640.c Drivers/BSP/Components/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32H747xx -DUSE_STM32H747I_DISCO -DCORE_CM7 -DDATA_IN_ExtSDRAM -DSTM32_IPL -DARM_MATH_CM7 -D__FPU_PRESENT=1U -DSTM32IPL -c -I../../../Inc/CM7 -I../../../../Network/Inc -I../../../../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../../../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/Components/Common -I../../../../../Drivers/BSP/Components/ov9655 -I../../../../../Drivers/BSP/Components/otm8009a -I../../../../../Drivers/BSP/Components/nt35510 -I../../../../../Drivers/BSP/Components/mt25tl01g -I../../../../../Utilities/Fonts -I../../../../../Utilities/lcd -I../../../../../Middlewares/ST/STM32_AI_Runtime/Inc -I../../../../../Middlewares/ST/STM32_ImageProcessing_Library/Inc -I../../../../../Middlewares/ST/STM32_Objdetect_Postprocess/Inc -I../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../Drivers/CMSIS/Core/Include -I../../../../../Drivers/CMSIS/Core/DSP/Include -I../../../../../Drivers/BSP/STM32H747I-DISCO -O3 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/Components/ov5640_reg.o: H:/stm32ai-modelzoo-2.1.0/stm32ai_application_code/object_detection/Drivers/BSP/Components/ov5640/ov5640_reg.c Drivers/BSP/Components/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32H747xx -DUSE_STM32H747I_DISCO -DCORE_CM7 -DDATA_IN_ExtSDRAM -DSTM32_IPL -DARM_MATH_CM7 -D__FPU_PRESENT=1U -DSTM32IPL -c -I../../../Inc/CM7 -I../../../../Network/Inc -I../../../../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../../../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/Components/Common -I../../../../../Drivers/BSP/Components/ov9655 -I../../../../../Drivers/BSP/Components/otm8009a -I../../../../../Drivers/BSP/Components/nt35510 -I../../../../../Drivers/BSP/Components/mt25tl01g -I../../../../../Utilities/Fonts -I../../../../../Utilities/lcd -I../../../../../Middlewares/ST/STM32_AI_Runtime/Inc -I../../../../../Middlewares/ST/STM32_ImageProcessing_Library/Inc -I../../../../../Middlewares/ST/STM32_Objdetect_Postprocess/Inc -I../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../Drivers/CMSIS/Core/Include -I../../../../../Drivers/CMSIS/Core/DSP/Include -I../../../../../Drivers/BSP/STM32H747I-DISCO -O3 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/Components/ov9655.o: H:/stm32ai-modelzoo-2.1.0/stm32ai_application_code/object_detection/Drivers/BSP/Components/ov9655/ov9655.c Drivers/BSP/Components/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32H747xx -DUSE_STM32H747I_DISCO -DCORE_CM7 -DDATA_IN_ExtSDRAM -DSTM32_IPL -DARM_MATH_CM7 -D__FPU_PRESENT=1U -DSTM32IPL -c -I../../../Inc/CM7 -I../../../../Network/Inc -I../../../../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../../../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/Components/Common -I../../../../../Drivers/BSP/Components/ov9655 -I../../../../../Drivers/BSP/Components/otm8009a -I../../../../../Drivers/BSP/Components/nt35510 -I../../../../../Drivers/BSP/Components/mt25tl01g -I../../../../../Utilities/Fonts -I../../../../../Utilities/lcd -I../../../../../Middlewares/ST/STM32_AI_Runtime/Inc -I../../../../../Middlewares/ST/STM32_ImageProcessing_Library/Inc -I../../../../../Middlewares/ST/STM32_Objdetect_Postprocess/Inc -I../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../Drivers/CMSIS/Core/Include -I../../../../../Drivers/CMSIS/Core/DSP/Include -I../../../../../Drivers/BSP/STM32H747I-DISCO -O3 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/Components/ov9655_reg.o: H:/stm32ai-modelzoo-2.1.0/stm32ai_application_code/object_detection/Drivers/BSP/Components/ov9655/ov9655_reg.c Drivers/BSP/Components/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32H747xx -DUSE_STM32H747I_DISCO -DCORE_CM7 -DDATA_IN_ExtSDRAM -DSTM32_IPL -DARM_MATH_CM7 -D__FPU_PRESENT=1U -DSTM32IPL -c -I../../../Inc/CM7 -I../../../../Network/Inc -I../../../../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../../../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/Components/Common -I../../../../../Drivers/BSP/Components/ov9655 -I../../../../../Drivers/BSP/Components/otm8009a -I../../../../../Drivers/BSP/Components/nt35510 -I../../../../../Drivers/BSP/Components/mt25tl01g -I../../../../../Utilities/Fonts -I../../../../../Utilities/lcd -I../../../../../Middlewares/ST/STM32_AI_Runtime/Inc -I../../../../../Middlewares/ST/STM32_ImageProcessing_Library/Inc -I../../../../../Middlewares/ST/STM32_Objdetect_Postprocess/Inc -I../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../Drivers/CMSIS/Core/Include -I../../../../../Drivers/CMSIS/Core/DSP/Include -I../../../../../Drivers/BSP/STM32H747I-DISCO -O3 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Drivers-2f-BSP-2f-Components

clean-Drivers-2f-BSP-2f-Components:
	-$(RM) ./Drivers/BSP/Components/mt25tl01g.cyclo ./Drivers/BSP/Components/mt25tl01g.d ./Drivers/BSP/Components/mt25tl01g.o ./Drivers/BSP/Components/mt25tl01g.su ./Drivers/BSP/Components/nt35510.cyclo ./Drivers/BSP/Components/nt35510.d ./Drivers/BSP/Components/nt35510.o ./Drivers/BSP/Components/nt35510.su ./Drivers/BSP/Components/nt35510_reg.cyclo ./Drivers/BSP/Components/nt35510_reg.d ./Drivers/BSP/Components/nt35510_reg.o ./Drivers/BSP/Components/nt35510_reg.su ./Drivers/BSP/Components/otm8009a.cyclo ./Drivers/BSP/Components/otm8009a.d ./Drivers/BSP/Components/otm8009a.o ./Drivers/BSP/Components/otm8009a.su ./Drivers/BSP/Components/otm8009a_reg.cyclo ./Drivers/BSP/Components/otm8009a_reg.d ./Drivers/BSP/Components/otm8009a_reg.o ./Drivers/BSP/Components/otm8009a_reg.su ./Drivers/BSP/Components/ov5640.cyclo ./Drivers/BSP/Components/ov5640.d ./Drivers/BSP/Components/ov5640.o ./Drivers/BSP/Components/ov5640.su ./Drivers/BSP/Components/ov5640_reg.cyclo ./Drivers/BSP/Components/ov5640_reg.d ./Drivers/BSP/Components/ov5640_reg.o ./Drivers/BSP/Components/ov5640_reg.su ./Drivers/BSP/Components/ov9655.cyclo ./Drivers/BSP/Components/ov9655.d ./Drivers/BSP/Components/ov9655.o ./Drivers/BSP/Components/ov9655.su ./Drivers/BSP/Components/ov9655_reg.cyclo ./Drivers/BSP/Components/ov9655_reg.d ./Drivers/BSP/Components/ov9655_reg.o ./Drivers/BSP/Components/ov9655_reg.su

.PHONY: clean-Drivers-2f-BSP-2f-Components

