################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (12.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
H:/stm32ai-modelzoo-2.1.0/stm32ai_application_code/object_detection/Middlewares/ST/STM32_ImageProcessing_Library/Src/imlib.c \
H:/stm32ai-modelzoo-2.1.0/stm32ai_application_code/object_detection/Middlewares/ST/STM32_ImageProcessing_Library/Src/stm32ipl.c \
H:/stm32ai-modelzoo-2.1.0/stm32ai_application_code/object_detection/Middlewares/ST/STM32_ImageProcessing_Library/Src/stm32ipl_convert.c \
H:/stm32ai-modelzoo-2.1.0/stm32ai_application_code/object_detection/Middlewares/ST/STM32_ImageProcessing_Library/Src/stm32ipl_image_io.c \
H:/stm32ai-modelzoo-2.1.0/stm32ai_application_code/object_detection/Middlewares/ST/STM32_ImageProcessing_Library/Src/stm32ipl_mem_alloc.c \
H:/stm32ai-modelzoo-2.1.0/stm32ai_application_code/object_detection/Middlewares/ST/STM32_ImageProcessing_Library/Src/stm32ipl_resize.c \
H:/stm32ai-modelzoo-2.1.0/stm32ai_application_code/object_detection/Middlewares/ST/STM32_ImageProcessing_Library/Src/umm_malloc.c 

OBJS += \
./Middlewares/STM32_ImageProcessing_Library/imlib.o \
./Middlewares/STM32_ImageProcessing_Library/stm32ipl.o \
./Middlewares/STM32_ImageProcessing_Library/stm32ipl_convert.o \
./Middlewares/STM32_ImageProcessing_Library/stm32ipl_image_io.o \
./Middlewares/STM32_ImageProcessing_Library/stm32ipl_mem_alloc.o \
./Middlewares/STM32_ImageProcessing_Library/stm32ipl_resize.o \
./Middlewares/STM32_ImageProcessing_Library/umm_malloc.o 

C_DEPS += \
./Middlewares/STM32_ImageProcessing_Library/imlib.d \
./Middlewares/STM32_ImageProcessing_Library/stm32ipl.d \
./Middlewares/STM32_ImageProcessing_Library/stm32ipl_convert.d \
./Middlewares/STM32_ImageProcessing_Library/stm32ipl_image_io.d \
./Middlewares/STM32_ImageProcessing_Library/stm32ipl_mem_alloc.d \
./Middlewares/STM32_ImageProcessing_Library/stm32ipl_resize.d \
./Middlewares/STM32_ImageProcessing_Library/umm_malloc.d 


# Each subdirectory must supply rules for building sources it contributes
Middlewares/STM32_ImageProcessing_Library/imlib.o: H:/stm32ai-modelzoo-2.1.0/stm32ai_application_code/object_detection/Middlewares/ST/STM32_ImageProcessing_Library/Src/imlib.c Middlewares/STM32_ImageProcessing_Library/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32H747xx -DUSE_STM32H747I_DISCO -DCORE_CM7 -DDATA_IN_ExtSDRAM -DSTM32_IPL -DARM_MATH_CM7 -D__FPU_PRESENT=1U -DSTM32IPL -c -I../../../Inc/CM7 -I../../../../Network/Inc -I../../../../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../../../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/Components/Common -I../../../../../Drivers/BSP/Components/ov9655 -I../../../../../Drivers/BSP/Components/otm8009a -I../../../../../Drivers/BSP/Components/nt35510 -I../../../../../Drivers/BSP/Components/mt25tl01g -I../../../../../Utilities/Fonts -I../../../../../Utilities/lcd -I../../../../../Middlewares/ST/STM32_AI_Runtime/Inc -I../../../../../Middlewares/ST/STM32_ImageProcessing_Library/Inc -I../../../../../Middlewares/ST/STM32_Objdetect_Postprocess/Inc -I../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../Drivers/CMSIS/Core/Include -I../../../../../Drivers/CMSIS/Core/DSP/Include -I../../../../../Drivers/BSP/STM32H747I-DISCO -O3 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/STM32_ImageProcessing_Library/stm32ipl.o: H:/stm32ai-modelzoo-2.1.0/stm32ai_application_code/object_detection/Middlewares/ST/STM32_ImageProcessing_Library/Src/stm32ipl.c Middlewares/STM32_ImageProcessing_Library/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32H747xx -DUSE_STM32H747I_DISCO -DCORE_CM7 -DDATA_IN_ExtSDRAM -DSTM32_IPL -DARM_MATH_CM7 -D__FPU_PRESENT=1U -DSTM32IPL -c -I../../../Inc/CM7 -I../../../../Network/Inc -I../../../../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../../../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/Components/Common -I../../../../../Drivers/BSP/Components/ov9655 -I../../../../../Drivers/BSP/Components/otm8009a -I../../../../../Drivers/BSP/Components/nt35510 -I../../../../../Drivers/BSP/Components/mt25tl01g -I../../../../../Utilities/Fonts -I../../../../../Utilities/lcd -I../../../../../Middlewares/ST/STM32_AI_Runtime/Inc -I../../../../../Middlewares/ST/STM32_ImageProcessing_Library/Inc -I../../../../../Middlewares/ST/STM32_Objdetect_Postprocess/Inc -I../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../Drivers/CMSIS/Core/Include -I../../../../../Drivers/CMSIS/Core/DSP/Include -I../../../../../Drivers/BSP/STM32H747I-DISCO -O3 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/STM32_ImageProcessing_Library/stm32ipl_convert.o: H:/stm32ai-modelzoo-2.1.0/stm32ai_application_code/object_detection/Middlewares/ST/STM32_ImageProcessing_Library/Src/stm32ipl_convert.c Middlewares/STM32_ImageProcessing_Library/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32H747xx -DUSE_STM32H747I_DISCO -DCORE_CM7 -DDATA_IN_ExtSDRAM -DSTM32_IPL -DARM_MATH_CM7 -D__FPU_PRESENT=1U -DSTM32IPL -c -I../../../Inc/CM7 -I../../../../Network/Inc -I../../../../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../../../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/Components/Common -I../../../../../Drivers/BSP/Components/ov9655 -I../../../../../Drivers/BSP/Components/otm8009a -I../../../../../Drivers/BSP/Components/nt35510 -I../../../../../Drivers/BSP/Components/mt25tl01g -I../../../../../Utilities/Fonts -I../../../../../Utilities/lcd -I../../../../../Middlewares/ST/STM32_AI_Runtime/Inc -I../../../../../Middlewares/ST/STM32_ImageProcessing_Library/Inc -I../../../../../Middlewares/ST/STM32_Objdetect_Postprocess/Inc -I../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../Drivers/CMSIS/Core/Include -I../../../../../Drivers/CMSIS/Core/DSP/Include -I../../../../../Drivers/BSP/STM32H747I-DISCO -O3 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/STM32_ImageProcessing_Library/stm32ipl_image_io.o: H:/stm32ai-modelzoo-2.1.0/stm32ai_application_code/object_detection/Middlewares/ST/STM32_ImageProcessing_Library/Src/stm32ipl_image_io.c Middlewares/STM32_ImageProcessing_Library/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32H747xx -DUSE_STM32H747I_DISCO -DCORE_CM7 -DDATA_IN_ExtSDRAM -DSTM32_IPL -DARM_MATH_CM7 -D__FPU_PRESENT=1U -DSTM32IPL -c -I../../../Inc/CM7 -I../../../../Network/Inc -I../../../../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../../../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/Components/Common -I../../../../../Drivers/BSP/Components/ov9655 -I../../../../../Drivers/BSP/Components/otm8009a -I../../../../../Drivers/BSP/Components/nt35510 -I../../../../../Drivers/BSP/Components/mt25tl01g -I../../../../../Utilities/Fonts -I../../../../../Utilities/lcd -I../../../../../Middlewares/ST/STM32_AI_Runtime/Inc -I../../../../../Middlewares/ST/STM32_ImageProcessing_Library/Inc -I../../../../../Middlewares/ST/STM32_Objdetect_Postprocess/Inc -I../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../Drivers/CMSIS/Core/Include -I../../../../../Drivers/CMSIS/Core/DSP/Include -I../../../../../Drivers/BSP/STM32H747I-DISCO -O3 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/STM32_ImageProcessing_Library/stm32ipl_mem_alloc.o: H:/stm32ai-modelzoo-2.1.0/stm32ai_application_code/object_detection/Middlewares/ST/STM32_ImageProcessing_Library/Src/stm32ipl_mem_alloc.c Middlewares/STM32_ImageProcessing_Library/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32H747xx -DUSE_STM32H747I_DISCO -DCORE_CM7 -DDATA_IN_ExtSDRAM -DSTM32_IPL -DARM_MATH_CM7 -D__FPU_PRESENT=1U -DSTM32IPL -c -I../../../Inc/CM7 -I../../../../Network/Inc -I../../../../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../../../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/Components/Common -I../../../../../Drivers/BSP/Components/ov9655 -I../../../../../Drivers/BSP/Components/otm8009a -I../../../../../Drivers/BSP/Components/nt35510 -I../../../../../Drivers/BSP/Components/mt25tl01g -I../../../../../Utilities/Fonts -I../../../../../Utilities/lcd -I../../../../../Middlewares/ST/STM32_AI_Runtime/Inc -I../../../../../Middlewares/ST/STM32_ImageProcessing_Library/Inc -I../../../../../Middlewares/ST/STM32_Objdetect_Postprocess/Inc -I../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../Drivers/CMSIS/Core/Include -I../../../../../Drivers/CMSIS/Core/DSP/Include -I../../../../../Drivers/BSP/STM32H747I-DISCO -O3 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/STM32_ImageProcessing_Library/stm32ipl_resize.o: H:/stm32ai-modelzoo-2.1.0/stm32ai_application_code/object_detection/Middlewares/ST/STM32_ImageProcessing_Library/Src/stm32ipl_resize.c Middlewares/STM32_ImageProcessing_Library/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32H747xx -DUSE_STM32H747I_DISCO -DCORE_CM7 -DDATA_IN_ExtSDRAM -DSTM32_IPL -DARM_MATH_CM7 -D__FPU_PRESENT=1U -DSTM32IPL -c -I../../../Inc/CM7 -I../../../../Network/Inc -I../../../../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../../../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/Components/Common -I../../../../../Drivers/BSP/Components/ov9655 -I../../../../../Drivers/BSP/Components/otm8009a -I../../../../../Drivers/BSP/Components/nt35510 -I../../../../../Drivers/BSP/Components/mt25tl01g -I../../../../../Utilities/Fonts -I../../../../../Utilities/lcd -I../../../../../Middlewares/ST/STM32_AI_Runtime/Inc -I../../../../../Middlewares/ST/STM32_ImageProcessing_Library/Inc -I../../../../../Middlewares/ST/STM32_Objdetect_Postprocess/Inc -I../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../Drivers/CMSIS/Core/Include -I../../../../../Drivers/CMSIS/Core/DSP/Include -I../../../../../Drivers/BSP/STM32H747I-DISCO -O3 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/STM32_ImageProcessing_Library/umm_malloc.o: H:/stm32ai-modelzoo-2.1.0/stm32ai_application_code/object_detection/Middlewares/ST/STM32_ImageProcessing_Library/Src/umm_malloc.c Middlewares/STM32_ImageProcessing_Library/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32H747xx -DUSE_STM32H747I_DISCO -DCORE_CM7 -DDATA_IN_ExtSDRAM -DSTM32_IPL -DARM_MATH_CM7 -D__FPU_PRESENT=1U -DSTM32IPL -c -I../../../Inc/CM7 -I../../../../Network/Inc -I../../../../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../../../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/Components/Common -I../../../../../Drivers/BSP/Components/ov9655 -I../../../../../Drivers/BSP/Components/otm8009a -I../../../../../Drivers/BSP/Components/nt35510 -I../../../../../Drivers/BSP/Components/mt25tl01g -I../../../../../Utilities/Fonts -I../../../../../Utilities/lcd -I../../../../../Middlewares/ST/STM32_AI_Runtime/Inc -I../../../../../Middlewares/ST/STM32_ImageProcessing_Library/Inc -I../../../../../Middlewares/ST/STM32_Objdetect_Postprocess/Inc -I../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../Drivers/CMSIS/Core/Include -I../../../../../Drivers/CMSIS/Core/DSP/Include -I../../../../../Drivers/BSP/STM32H747I-DISCO -O3 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Middlewares-2f-STM32_ImageProcessing_Library

clean-Middlewares-2f-STM32_ImageProcessing_Library:
	-$(RM) ./Middlewares/STM32_ImageProcessing_Library/imlib.cyclo ./Middlewares/STM32_ImageProcessing_Library/imlib.d ./Middlewares/STM32_ImageProcessing_Library/imlib.o ./Middlewares/STM32_ImageProcessing_Library/imlib.su ./Middlewares/STM32_ImageProcessing_Library/stm32ipl.cyclo ./Middlewares/STM32_ImageProcessing_Library/stm32ipl.d ./Middlewares/STM32_ImageProcessing_Library/stm32ipl.o ./Middlewares/STM32_ImageProcessing_Library/stm32ipl.su ./Middlewares/STM32_ImageProcessing_Library/stm32ipl_convert.cyclo ./Middlewares/STM32_ImageProcessing_Library/stm32ipl_convert.d ./Middlewares/STM32_ImageProcessing_Library/stm32ipl_convert.o ./Middlewares/STM32_ImageProcessing_Library/stm32ipl_convert.su ./Middlewares/STM32_ImageProcessing_Library/stm32ipl_image_io.cyclo ./Middlewares/STM32_ImageProcessing_Library/stm32ipl_image_io.d ./Middlewares/STM32_ImageProcessing_Library/stm32ipl_image_io.o ./Middlewares/STM32_ImageProcessing_Library/stm32ipl_image_io.su ./Middlewares/STM32_ImageProcessing_Library/stm32ipl_mem_alloc.cyclo ./Middlewares/STM32_ImageProcessing_Library/stm32ipl_mem_alloc.d ./Middlewares/STM32_ImageProcessing_Library/stm32ipl_mem_alloc.o ./Middlewares/STM32_ImageProcessing_Library/stm32ipl_mem_alloc.su ./Middlewares/STM32_ImageProcessing_Library/stm32ipl_resize.cyclo ./Middlewares/STM32_ImageProcessing_Library/stm32ipl_resize.d ./Middlewares/STM32_ImageProcessing_Library/stm32ipl_resize.o ./Middlewares/STM32_ImageProcessing_Library/stm32ipl_resize.su ./Middlewares/STM32_ImageProcessing_Library/umm_malloc.cyclo ./Middlewares/STM32_ImageProcessing_Library/umm_malloc.d ./Middlewares/STM32_ImageProcessing_Library/umm_malloc.o ./Middlewares/STM32_ImageProcessing_Library/umm_malloc.su

.PHONY: clean-Middlewares-2f-STM32_ImageProcessing_Library

